# Define needed environment variables: the rest of the yml will most
# likely translate well to other similar projects, except for the
# "secure" passwords in the deploy stage, which have to be adapted.
env:
  global:
    # test stage config
    - CODECOV_REQUIRED_PERCENT="50.0" # for utest+codecov
    # - MAX_MB_ALLOWED="512" # for mem benchmark
    # - MEM_MEASURE_EVERY_SEC="0.05" # in seconds, measure memory at these intervals
    # - MAX_SEC_PER_LOOP="5.0" # for time benchmark
    # build stage config
    - DOC_PACKAGE_NAME="audio_synch_tool"
    - DOC_AUTHOR_NAME="Andres FR"
    - BUMPVERSION_FILE=".bumpversion.cfg"
    # deploy stage config
    - PYPI_USERNAME="fr_andres"
    - GH_RELEASES_ASSET_PATH="dist/*" # all matches for this path will be included into the GitHub release
    - REPO_NAME="andres-fr/audio-synch-tool" # releases will only work under this name
    - CHANGELOG_PATH="CHANGELOG.md" # relative to repo root

# this line routes the builds to Ubuntu 16.04
dist: xenial

# implicitly creates a venv for python in the VM (so pip syntax is "global")
language: python
python:
  - 3.7

# by default Travis starts every job from scratch. This speeds up things
cache: pip

# Perform pipeline only for events to master branch
branches:
  only:
  - master
  # this is needed for tag push actions (https://github.com/travis-ci/travis-ci/issues/8518#issuecomment-333489268)
  - /^v.*$/

#  https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  # - osx
  #- windows

install: pip install -r requirements.txt


addons:
  apt:
    packages:
      - latexmk
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - texlive-latex-extra
  # homebrew:
  #   packages: ...

# here we define the stages. stage ordering will come later
jobs:
  include:
    # Perform all needed tests to ensure repo quality. All scripts
    # in a stage are done in parallel. Stages are done sequentially.
    - stage: test
      name: "Check Code Style"
      script: python -m flake8
    - script: python -m unittest audio_synch_tool_utest/tautology.py
      name: "Tautological Test"
    - script: python ci_scripts/utest_with_coverage.py -n "$DOC_PACKAGE_NAME" -p "$CODECOV_REQUIRED_PERCENT"
      name: "Unit Testing and Code Coverage"
    # - script: python ci_scripts/memory_benchmark.py -m "$MAX_MB_ALLOWED" -i "$MEM_MEASURE_EVERY_SEC"
    #   name: "Memory Benchmarking"
    # - script: python ci_scripts/runtime_benchmark.py -m "$MAX_SEC_PER_LOOP"
    #   name: "Runtime Benchmarking"

    # If all tests pass, go on to the build stage
    - stage: build
      script: python setup.py sdist bdist_wheel
      name: "Build Package"
    - script: python ci_scripts/make_sphinx_docs.py -n "$DOC_PACKAGE_NAME" -a "$DOC_AUTHOR_NAME" -f "$BUMPVERSION_FILE" -o "docs" -l
      name: "Build Autodocs"

    # If building was successful, deploy to various platforms
    - stage: deploy
      before_script: python setup.py sdist bdist_wheel # since we are deploying in a proper stage, the repo starts from scratch and needs to rebuild.
      script: echo ""
      name: "Deploy to GitHub Releases and PyPI"
      deploy:
        - provider: releases
          skip_cleanup: true
          name: "$TRAVIS_COMMIT_MESSAGE"
          body: "See [CHANGELOG]($CHANGELOG_PATH) for details."
          api_key:
            secure: "j9rLBizLl99v86vKjQNxaxkp9XcuJ0noUAI/C/XicN/6dDoCdscbngJW383SJp85t9/0XtuPSFW8sq9V2sxzGdCdr2WR8WOf33U50sMF0yzLPIEZ2trreEmoysQKN4G23wE5NB/QONrEZfnHKQE0MJz0/NNUmPjgXGbr0xqjb1/NVL+RSiSJ6EtlpH6yKxiIOkfM6cB9R4Y3xMV4q+2E8R0jq/Nj230dgnKp4a584meJzufnLxHd7397oC80uDx3CTNUdlAsEvZLjlXBNOdVmS4mov11Qo293cA6VNDRgoTht7ozAeA8K5XvDoyJu2d0Hkj11vOtF7n5AYHPdXOHL8k+Dk6+YCshEx2RgvXu/Cpzmh+ACl6juHx1u/L1W879M7sEDmmNQDpcmL0Te9DMPA34va2TfTPPsVv9GjYRIZAJ6w+Fi0XppzPXylzPPQxjoRN2lhmNOiG4PnYA04dJAA9vB45HU2BI4UYZbOMnE9tA8zw8dy+dexOFST0x1P5QXTfqc1m9l3R0ZIpaPztyrwjDcQxTDJz7aMbRLUEPEss5Ixhe2X+9rSM6la1RJ5VnIc0cxUYtbpfds/NNkt1xEawXpHwQtNhNgDVzIEBKyGjcOh6vTQR7UuxVrvv6otsu6xc2qxW4bcTMmc7EIplLaKFpS2QkiMEfKl/FFffxTko="
          file_glob: true
          file: "$GH_RELEASES_ASSET_PATH"
          on:
            tags: true
            # branch: master # already filtered out in the "branches" section
            repo: "$REPO_NAME"
        - provider: pypi
          skip_cleanup: true
          user: "$PYPI_USERNAME"
          password:
            secure: "aH6EytG8v8XM5a9gDAGbeyGFBHQkUXYn5kAfN+46UOKCxp9T8N0tJfMcc7gPp425HdHgjF4SRF2gv273Yfn4x5gNV6gq6doAd5eCnFVeZvjLTQcJgytWhEuQ/DvQV4pTcxCMOVDBj5+jR6bz6ShLUP5XJ50Oycyj0UUb7cFGBArPPMiHEQEA973mKGtJm3SPKXN/763j7GULtsv2sP7v6KsUfaXiRv8IjT0jv4Gx8i//usOWB6HV8bpQ39ax2XMm7cPZ8bGorL/SIIHfz6YI0hYkLQN3fiaBLAp35dO1kFxKE4Ger3BKU/sSv6PdgL2UCDJKowjjFqVA1b01JVyInFitP/GVSHluTH3T5QJ6h5wXtYHlcCbQcDZ3wln1ExHLberVWGjh7GmxfVriMY2Ju81BnqhPUIlYExZ3M6qvu7N0619DDGilBcLH08/D+S5VJrBzFsj28h6oigrTSde49arkr+1tKliCKOb3MbmIIEY2ExBiLN6i5xM4pOMgu8F+njs4MAckbDcRDRgPxBdf6fqeFK5shd/AfKSVcoMbqucLS7w/RiVXEeQ+/e0+2Kznqnqayus23jmHPf4bPGU70R3P3X82viT4RR6YR3EEGtkciQ2U1LrRY5XIoKC5qL6CBpHefrarcAPrDPK6k+sR2uTPOSmgzVot8TxUprO0PNE="
          on:
            tags: true
            # branch: master # already filtered out in the "branches" section
            repo: "$REPO_NAME"


# Here you can specify the order for stages, or skip some
stages:
  - test
  - build
  - deploy
